name: Sync Scoop Official Buckets

on:
  schedule:
    # 每天北京时间早上8点运行 (UTC时间0点)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发
    inputs:
      bucket:
        description: 'Specific bucket to sync (leave empty for all)'
        required: false
        default: ''

env:
  TZ: Asia/Shanghai

jobs:
  sync-buckets:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        bucket:
          - name: main
            repo: ScoopInstaller/Main
          - name: extras  
            repo: ScoopInstaller/Extras
          - name: versions
            repo: ScoopInstaller/Versions
          - name: nirsoft
            repo: ScoopInstaller/Nirsoft
          - name: php
            repo: ScoopInstaller/PHP
          - name: nonportable
            repo: ScoopInstaller/Nonportable
          - name: java
            repo: ScoopInstaller/Java
          - name: games
            repo: Calinou/scoop-games
          - name: nerd-fonts
            repo: matthewjberger/scoop-nerd-fonts
          - name: sysinternals
            repo: niheaven/scoop-sysinternals
    
    steps:
    - name: Checkout repository
      if: github.event.inputs.bucket == '' || github.event.inputs.bucket == matrix.bucket.name
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Git
      if: github.event.inputs.bucket == '' || github.event.inputs.bucket == matrix.bucket.name
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Skip if specific bucket requested
      if: github.event.inputs.bucket != '' && github.event.inputs.bucket != matrix.bucket.name
      run: |
        echo "Skipping ${{ matrix.bucket.name }} - only syncing ${{ github.event.inputs.bucket }}"
        exit 0

    - name: Check existing files
      if: github.event.inputs.bucket == '' || github.event.inputs.bucket == matrix.bucket.name
      id: check_existing
      run: |
        if [ -d "buckets/${{ matrix.bucket.name }}" ]; then
          existing_count=$(find buckets/${{ matrix.bucket.name }} -name "*.json" | wc -l)
          echo "existing_count=$existing_count" >> $GITHUB_OUTPUT
          echo "Found $existing_count existing files in buckets/${{ matrix.bucket.name }}"
        else
          echo "existing_count=0" >> $GITHUB_OUTPUT
          echo "No existing files found for ${{ matrix.bucket.name }}"
        fi

    - name: Clone source repository
      if: github.event.inputs.bucket == '' || github.event.inputs.bucket == matrix.bucket.name
      run: |
        echo "Cloning ${{ matrix.bucket.repo }}..."
        # 创建临时目录
        mkdir -p temp_sync
        cd temp_sync
        
        # 克隆源仓库（仅bucket目录）
        git clone --filter=blob:none --sparse https://github.com/${{ matrix.bucket.repo }}.git source_repo
        cd source_repo
        git sparse-checkout set bucket
        
        # 统计文件数量
        if [ -d "bucket" ]; then
          total_files=$(find bucket -name "*.json" | wc -l)
          echo "Found $total_files JSON files in source repository"
          
          # 创建目标目录
          mkdir -p ../../buckets/${{ matrix.bucket.name }}
          
          # 复制所有JSON文件
          echo "Copying JSON files..."
          find bucket -name "*.json" -exec cp {} ../../buckets/${{ matrix.bucket.name }}/ \;
          
          # 验证复制结果
          copied_files=$(find ../../buckets/${{ matrix.bucket.name }} -name "*.json" | wc -l)
          echo "Successfully copied $copied_files files to buckets/${{ matrix.bucket.name }}"
        else
          echo "No bucket directory found in source repository"
        fi
        
        # 清理临时目录
        cd ../..
        rm -rf temp_sync

    - name: Commit changes for this bucket
      if: github.event.inputs.bucket == '' || github.event.inputs.bucket == matrix.bucket.name
      run: |
        # 检查是否有变化
        if git diff --quiet buckets/${{ matrix.bucket.name }}/; then
          echo "No changes detected for ${{ matrix.bucket.name }}"
        else
          echo "Changes detected for ${{ matrix.bucket.name }}, committing..."
          git add buckets/${{ matrix.bucket.name }}/
          
          # 统计文件数量
          file_count=$(find buckets/${{ matrix.bucket.name }} -name "*.json" | wc -l)
          
          git commit -m "Update ${{ matrix.bucket.name }} bucket - $file_count files ($(date '+%Y-%m-%d %H:%M:%S'))"
          echo "Committed changes for ${{ matrix.bucket.name }}"
        fi

    - name: Push changes
      if: github.event.inputs.bucket == '' || github.event.inputs.bucket == matrix.bucket.name
      run: |
        if git log origin/main..HEAD --oneline | grep -q .; then
          echo "Pushing changes for ${{ matrix.bucket.name }}..."
          git push origin main
          echo "Successfully pushed changes for ${{ matrix.bucket.name }}"
        else
          echo "No new commits to push for ${{ matrix.bucket.name }}"
        fi

  update-readme:
    needs: sync-buckets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Pull latest changes
      run: git pull origin main
    
    - name: Update README timestamp and statistics
      run: |
        current_time=$(TZ=Asia/Shanghai date '+%Y年%m月%d日 %H:%M:%S')
        
        # 创建临时文件来重新生成README
        cp README.md README_temp.md
        
        # 移除旧的统计信息部分（从"最后更新时间"到文件末尾）
        sed -i '/最后更新时间:/,$d' README_temp.md
        
        # 添加新的时间戳
        echo "最后更新时间: $current_time" >> README_temp.md
        echo "" >> README_temp.md
        
        # 添加新的统计信息
        echo "## 统计信息" >> README_temp.md
        echo "" >> README_temp.md
        
        total_count=0
        for bucket in main extras versions nirsoft php nonportable java games nerd-fonts sysinternals; do
          if [ -d "buckets/$bucket" ]; then
            count=$(find buckets/$bucket -name "*.json" | wc -l)
            if [ "$count" -gt 0 ]; then
              echo "- $bucket: $count 个应用程序" >> README_temp.md
              total_count=$((total_count + count))
            fi
          fi
        done
        echo "" >> README_temp.md
        echo "总计: $total_count 个应用程序" >> README_temp.md
        
        # 替换原文件
        mv README_temp.md README.md
        
        echo "Updated README with $total_count total applications"
    
    - name: Commit README update
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add README.md
        if git diff --cached --quiet; then
          echo "No changes to commit for README"
        else
          git commit -m "Update README with latest statistics - $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
